Add charge holy weapon
rpherbig/dr-scripts pull request #4572
Opened 2020-10-26 04:30 UTC by jayRyan24

Will find out the data for crossing and submit it.

2020-10-26 04:41 UTC, jayRyan24 commented
My intention is to update this for Icons once I can get my hands on one!

2020-10-26 15:00 UTC, rpherbig requested changes

2020-10-26 15:01 UTC, rpherbig commented
Looks good ✔️  - only the change to `custom_require` is required.

2020-10-26 16:37 UTC, jayRyan24 commented
> Looks good ✔️ - only the change to `custom_require` is required.

All good suggestions, the timer one was one I thought about myself. Thanks!

2020-10-26 16:38 UTC, jayRyan24 commented on charge-holy-weapon.lic
> +    @settings = get_settings
I thought I might use it later, but makes sense to not control it instance wide.

2020-10-26 16:41 UTC, jayRyan24 commented
Just got an icon. I will add to this.

2020-10-26 18:22 UTC, jayRyan24 commented
Added icon support, and changed up the layout of the hash used for the data.

2020-10-26 21:31 UTC, rpherbig commented on charge-holy-weapon.lic
> +    bput('open my #{container}', 'You open')
❌ This won't do string interpolation unless it uses double quotes

2020-10-26 21:38 UTC, rpherbig commented on charge-holy-weapon.lic
> +    case bput("get my #{name}", 'You get', 'What were')
💡 If `container` was specified, is there any value to being more specific (e.g. `get my name from my container`)?

2020-10-26 23:01 UTC, jayRyan24 commented
@rpherbig I marked all the change requests as resolved, unsure what's going on with it still marking it as such. Unless you need to mark them as resolved? Thanks for the feedback and catches!

2020-10-27 14:02 UTC, rpherbig approved these changes

2020-10-27 14:03 UTC, rpherbig commented
> I marked all the change requests as resolved, unsure what's going on with it still marking it as such. Unless you need to mark them as resolved?

Yep, I need to update my review. Done.

2020-10-27 14:03 UTC, merged