[script][combat-trainer] - Refactor egg and warhorn use
rpherbig/dr-scripts pull request #5922
Opened 2022-07-17 15:47 UTC by asechrest

Refactors egg and warhorn use, allows rotating of each.

Draft until final cleanup.

2022-07-17 21:49 UTC, MahtraDR requested changes

2022-07-17 21:49 UTC, MahtraDR commented on profiles/base.yaml
> +@warhorn_cooldown: 1200
```suggestion
warhorn_cooldown: 1200
```

2022-07-17 22:04 UTC, asechrest commented
First tests by `sharkbait` on Discord are positive. He has an egg, as well as an auction warhorn with a 15 minute cooldown. It's cycling for him, with fairly tight timers. It's honoring the 10 minute room effect and cycling the egg and warhorn between 10 and 13 minutes after the last effect.

Waiting for additional testers who have only an egg, only a warhorn, and also someone using the legacy `warhorn: egg` setting.

2022-07-18 15:06 UTC, asechrest commented
@MahtraDR reports some issues with legacy use of `warhorn: egg` in this PR. It sometimes does nothing at all.

Also some funkiness with the cycle timers reported by @sharkbait where it skips the 20 minute mark, which should be a point where the timers work when cycling.

So this needs a bit more work.

2022-07-24 14:50 UTC, asechrest commented
@rpherbig @MahtraDR 

Ready for final review. Testers were: Gildaren (warhorn only), Mahtra (egg only), Sharkbait (egg and warhorn rotation, plus egg only on a thief).

Updating the original comment now with a summary of changes.

2022-07-25 03:01 UTC, merged